spring:
  cloud:
    stream:
      binders:
        private-binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: user
                host: ${rabbitmq.host}
                port: ${rabbitmq.port}
                username: ${rabbitmq.username}
                password: ${rabbitmq.password}
        public-binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: public
                host: ${rabbitmq.host}
                port: ${rabbitmq.port}
                username: ${rabbitmq.username}
                password: ${rabbitmq.password}
      rabbit:
        bindings:
          # ---------------------------------------
          # Private Outgoing RabbitMQ bindings
          ## User Created Event
          userCreatedEvent-out-0:
            producer:
              exchangeType: topic
              destination: private.user.exchange
              routingKeyExpression: "'user.created'"
          userCreatedEventError-out-0:
            producer:
              exchangeType: topic
              destination: private.user.exchange.error
              routingKeyExpression: "'user.created'"
              queueNameGroupOnly: true
          # ---------------------------------------
          # ---------------------------------------
          # Private Incoming RabbitMQ bindings
          ## User Created Event
          userCreatedEvent-in-0:
            consumer:
              exchangeType: topic
              bindingRoutingKey: user.created
              queueNameGroupOnly: true
              autoBindDlq: true
              deadLetterExchange: private.user.exchange.wait
              deadLetterQueueName: private.user.created.queue.wait
              dlqDeadLetterExchange: private.user.exchange
              dlqDeadLetterRoutingKey: user.created
              republishToDlq: false
              dlqTtl: 5000
          # ---------------------------------------
          # Public Outgoing RabbitMQ bindings
          ## User Created Event Integration
          userCreatedIntegrationEventV1-out-0:
              producer:
                exchangeType: topic
                destination: user.exchange
                routingKeyExpression: "'user.created.v1'"
          # ---------------------------------------
          # Public Incoming RabbitMQ bindings
          ## (Add public incoming bindings here if needed)
          # ---------------------------------------

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:rabbitmq}
  password: ${RABBITMQ_PASSWORD:rabbitmq}
